### ISSUE TITLE
Allow for quick check of number of mementos for a URI

### ISSUE THREAD

**Issue by machawk1** [machawk1/wail#10]

**Comment by machawk1** [comment]
@phonedude @weiglemc: this is an old issue in WAIL that I think you suggested at one point, pre-Mink ( https://github.com/machawk1/mink ). Do you think it still has a place in WAIL? Would it be useful to know how many mementos are in YOUR archive for a URI? Should we allow WAIL to also hit the aggregators/public archives?

**Comment by phonedude** [comment]
My gut reaction is that both would be useful.  My archiving strategy might change if I knew how many copies I had as well as how many copies are in the public web archives.

**Comment by machawk1** [comment]
Closing. Completed long ago with MemGator integration.
