### ISSUE TITLE
Display a breakdown of memento information as supplied by memgator from the basic WAIL interface

### ISSUE THREAD

**Issue by machawk1** [machawk1/wail#215]
@ibnesayeed, would it be best to keep with the native interface, forward over to a web-based one from WAIL, to communicate w/ MemGator's JSON interface (& parse/style) or to wait for whatever HTML formatted output you expect to have from MemGator?

**Comment by ibnesayeed** [comment]
I think it is better to utilize the JSON format which has stronger promise to live and be supported by different implementations as it is documented by LANL's Time Travel service API. Any other format will be experimental.

**Comment by machawk1** [comment]
ok. Would it be best to go from the native app to a web interface to display memento metadata or keep everything within the native app?

**Comment by ibnesayeed** [comment]
It depends on the context. It might be helpful to keep it within the application if that is where the users will be paying attention when interacting with the system. I would suggest neither to introduce a separate isolated web interface for the info nor to pollute the replay system's interface as much as possible.

**Comment by machawk1** [comment]
The idea of a web interface was to be independent of a replay system but rather, as another means of visualizing the TimeMap in a more aesthetic way than the text-based link header's contents. I'm leaning toward keeping it native though JSON seems less like the fitting choice if not querying from JS.

**Comment by ibnesayeed** [comment]
I think I can comment on it further only after conceiving your idea properly. We can discuss it in person when you come to the office.
