### ISSUE TITLE
Electron branch build from source requires correct starting directory

### ISSUE THREAD

**Issue by machawk1** [machawk1/wail#257]
In the electron branch, running the first command `npm install` shows the error:

``` sh
$ npm install
sequin@0.1.0 node_modules/faye/node_modules/csprng/node_modules/sequin -> node_modules/sequin
npm WARN enoent ENOENT: no such file or directory, open '/Users/machawk1/package.json'
npm WARN machawk1 No description
npm WARN machawk1 No repository field.
npm WARN machawk1 No README data
npm WARN machawk1 No license field.
```

doing `cd electron` seems to fix this and after doing so, the requirements are smoothly installed. This might be an artifact of git, as the source for the electron code is in a directory named "electron" in the root of my working copy of the repo. I am doing a pull like so:

`git clone --single-branch --branch electron https://github.com/N0taN3rd/wail`

@N0taN3rd , what command are you using to pull a local copy via git? Do you have to first `cd` into an `electron` directory?

**Comment by N0taN3rd** [comment]
@machawk1 You do have to cd into electron directory  first to do the build. I kept the directory structure of the orginal project and simply put the electron portion in its own directory.

**Comment by machawk1** [comment]
@N0taN3rd If that's the case, this extra command ought to be added to the build instructions.

**Comment by machawk1** [comment]
Electron branch forked off to https://github.com/N0taN3rd/wail awhile back with lots of work in that repo. Consult there for other outstanding issues until we get the code bases together again.
