### ISSUE TITLE
Enhancement: The ability to add multiple seeds at once

### ISSUE THREAD

**Issue by HussamHallak** [machawk1/wail#275]
WAIL does not allow the addition of multiple seeds. It can be enhanced to accept multiple seeds, or read them from a text file.

**Comment by machawk1** [comment]
@HussamHallak WAIL does have the ability to provide multiple seeds.

![screen shot 2017-11-29 at 9 45 09 pm](https://user-images.githubusercontent.com/2514780/33410503-9b08663e-d54e-11e7-863a-6992d6d38e8d.png)

If you have an issue using this functionality, please report back on this ticket. As there is the possibility that you meant to report this on https://github.com/n0tan3rd/wail (WAIL-Electron), please do so there.

/cc @weiglemc
