### ISSUE TITLE
Show number of archives represented in memento count in UI

### ISSUE THREAD

**Issue by machawk1** [machawk1/wail#282]
Currently we show the "number of mementos" within the window interface based on what the user entered in the text box. It would also be useful to show the number of archives from which these mementos originate. This information may need to be parsed out of the TimeMap returned from MemGator.

<img width="512" alt="screen shot 2017-12-14 at 1 20 43 pm" src="https://user-images.githubusercontent.com/2514780/34007936-9fd814b4-e0d1-11e7-86f7-11b13e46d24a.png">

**Comment by ibnesayeed** [comment]
Once implemented, https://github.com/oduwsdl/memgator/issues/97 should make it very easy, while also providing more summary information.

**Comment by machawk1** [comment]
@ibnesayeed In the meantime, since we are just looking for a count of archives, I am thinking of just clustering based on archival host. Thoughts?

**Comment by ibnesayeed** [comment]
That is certainly doable and can be easily implemented using a [Counter dict](https://docs.python.org/2/library/collections.html#collections.Counter). However, It might result in a slight delay for larger TMs. Currently, the total memento count can be accessed from the header even before the payload is fully downloaded (or just by making a HEAD request). Providing more information would require us to download the TM, parse it (or go through it one record/line at a time) to populate the counter dictionary before injecting the outcome in the UI.

**Comment by machawk1** [comment]
Thanks for the pointer.

It's running locally and performed asynchronously, so should not incur too much delay. I would like to either move away from calling URI-Ms in the returned TimeMap "mementos" or be more clear on [the basis of the count](https://arxiv.org/abs/1703.03302). Thus, relying on the X-Memento-Count header would be in a step in the opposite direction of what should be conveyed in the UI.

Also, performing a HEAD would still incur the delay of requesting the TimeMaps from the respective archives, which I believe is still much more significant than the delay to parse the TimeMap locally.

Also also, I'm using MemGator in one-off mode, not server mode, so the aforementioned is moot. I will be changing it to server mode once MemGator support runtime specification of archives (as is sub-optimally implemented in the http://github.com/oduwsdl/memgator fork).

**Comment by ibnesayeed** [comment]
@machawk1, I have added a couple comments in your recent commit.

* https://github.com/machawk1/wail/commit/76a6d4dc41ba17eb0b7ba65d6da2322c7f97c0b2#r26302085
* https://github.com/machawk1/wail/commit/76a6d4dc41ba17eb0b7ba65d6da2322c7f97c0b2#r26302196
