### ISSUE TITLE
Make execution/testing with Docker more efficient

### ISSUE THREAD

**Issue by machawk1** [machawk1/wail#405]
Testing with Docker requires a long delay after changing the code before the tweak can be tested. In other projects (e.g., [ipwb](https://github.com/oduwsdl/ipwb)), we have used waypoints/tags/othernomenclature to allow "sub-images" alraedy built to be reused:

e.g., `FROM       node`

This may speed up rebuilds and not require dependencies to be fetched.

**Comment by machawk1** [comment]
@ibnesayeed Can you make suggestions here based on [the Dockerfile](https://github.com/machawk1/wail/blob/osagnostic/Dockerfile) for iterative testing while progressively improving the code?

**Comment by ibnesayeed** [comment]
There are a bunch of optimizations that can be done to improve the cache utilization of the Docker image. I will see if I can create a PR for that.

**Comment by ibnesayeed** [comment]
#406 should take care of it.
