### ISSUE TITLE
Is wail being actively maintained?

### ISSUE THREAD

**Issue by LaazV** [machawk1/wail#479]
I tried running on Windows and managed to fix a few issues, to the point where the Wail, IA and Heritrix are apparently running, as well as the webserver, but I'm stuck in an eternal "Writing crawl configuration" when trying to archive any page. 

I can have a go in trying stuff out next week after I get some school work done if the project is still being maintained and there's interest to keep it up.. it still looks like it's the best bet for archival using Windows.. 

I've read #463  but it looks like it stalled..

**Comment by machawk1** [comment]
Hi @LaazV, I have been steadily working on getting the Windows version of WAIL back in shape but it has been slow going. Please do submit a PR if you have fixes or report any issues you have with the current master.
