### ISSUE TITLE
Version 0.2013.4.16 is unstable on MacOS X 10.9

### ISSUE THREAD

**Issue by machawk1** [machawk1/wail#54]
@trobbins reported for MacOS X 10.9.1 that on-launch the app immediately crashes.

Errors shown:
kernel[0]: Sandbox: mdworker(1713) deny file-read-xattr /Applications/WAIL
com.apple.launchd.peruser.503[332]: ([0x0-0xeb0eb].WAIL[2101]) Exited with code: 255

even with app in /Applications/

Re-downloading did not fix the problem.

**Comment by machawk1** [comment]
Needs verification for backward compatibility now that the src is more stable.

**Comment by machawk1** [comment]
Closing this issue since:
1. Many bugs have been fixed
1. A new release of WAIL exists
1. The current version of macOS is 10.14.2 (>> 10.9)

Admittedly, this is a crappy way to have to close a ticket. @todrobbins The new version (0.2017.07.26) ought to be a bit more stable but the latest master has bug fixes even beyond that. I have not pushed a new release in a while because development hell of wanting to also get a stable Windows version has prevent this.

If you are still running 10.9, please let me know! If you are using a new version of macOS, I invited you to test out WAIL 0.2017.07.26 or (if you're ambitious) compile the latest master from source.

Thanks again for the report years ago. :)

**Comment by todrobbins** [comment]
Running 0.2017.07.26 without a hiccup! Thanks again @machawk1!

![screen shot 2019-01-14 at 9 04 37 am](https://user-images.githubusercontent.com/158590/51124402-79305c80-17db-11e9-9e55-9186d134a05e.png)
