### ISSUE TITLE
Update to build with Python 3.10 (dependent on wxPython support)

### ISSUE THREAD

**Issue by machawk1** [machawk1/wail#543]
Pyinstaller does not yet support Py 3.10 when using the releases, though this was slated to be updated with a new release of Pyinstaller following the release of Py 3.10.

https://github.com/pyinstaller/pyinstaller/issues/5693

Currently building WAIL w/ the latest release of Pyinstaller on macOS 11.6 arm64 Py 3.10 fails.

- [ ] Try recompiling wxPython from source using 3.10 then rebuilding.

**Comment by machawk1** [comment]
This might be resolve with https://github.com/pyinstaller/pyinstaller/pull/5694.

**Comment by machawk1** [comment]
A new version of pyinstaller with support for Python 3.10 was released on October 29, 2021.

**Comment by machawk1** [comment]
wxPython appears to not support Python 3.10 as of release 4.1.1. Full trace attached due to GitHub rejecting it in a comment due to length:

[wxpython411_python_310.txt](https://github.com/machawk1/wail/files/7462149/wxpython411_python_310.txt)

**Comment by machawk1** [comment]
https://discuss.wxpython.org/t/serious-upgrade-problem/35604 suggests that building wxPython from source using Python 3.10 might remedy the issue.

**Comment by machawk1** [comment]
Installing snapshots of wxPython: https://wxpython.org/Phoenix/snapshot-builds/README.txt

**Comment by machawk1** [comment]
https://github.com/wxWidgets/Phoenix/issues/2128 shows some users still waiting on an official wheel that supports Python 3.10.

**Comment by ChrisBarker-NOAA** [comment]
Yup -- and a new release would be nice in any case :-)

@RobinD42: I notice you've pushed changes lately -- let us know if you need some help getting a release out.

**Comment by machawk1** [comment]
wxPython was released on August 7, 2022, so this should be re-tested.
