### ISSUE TITLE
Integrate pywb as an alterative replay system for the generated WARCs

### ISSUE THREAD

**Issue by machawk1** [machawk1/wail#74]
warc-proxy is already halfheartedly integrated but other tools (e.g., @ikreymer 's pywb ) are probably more suitable.

**Comment by ikreymer** [comment]
It turns out that pyinstaller will work if pywb is built as an egg and `zip_safe=True` is set.
I'll make that change for next release.

I've successfully built a one file executable. The only other files needed are the `config.yaml` and the warcs/cdx directories.

**Comment by machawk1** [comment]
@ikreymer Are the WARC/CDX directories set in the config.yaml file or on pywb launch? I currently have configs for OpenWayback and Heritrix setup to read/write from the same directory. I am hoping to get pywb to consult these same directories.

Exciting news on pywb being able to be compiled to a single file. :)

**Comment by ikreymer** [comment]
Yes, in the default run path, pywb reads the config from the yaml file (which can also be changed via an environment variable).

It's also possible to init pywb directly from python by calling the init_app function in `wayback.py`

In the case of WAIL, i think pywb egg could just embedded into the WAIL app.

I'll try to come up with a clear example of this.

In the meantime, you can take a look at how perma.cc uses pywb (without a yaml file):

https://github.com/harvard-lil/perma/blob/cbd381d58d20a5c4bf088b1bec9c1de052157855/perma_web/warc_server/app.py
(the custom app)

https://github.com/harvard-lil/perma/blob/cbd381d58d20a5c4bf088b1bec9c1de052157855/perma_web/warc_server/pywb_config.py (the programmatic config which has some custom extensions for perma, probably don't need all the custom stuff in your case, but an example of non-yaml config)

I am currently considering simplifying this further in a future release.

**Comment by ikreymer** [comment]
Quick update: pywb 0.7.5 has been released with `zip_safe=True` setting, and added support for running Windows.

**Comment by machawk1** [comment]
Closing this as complete in the form of WAIL-Electron https://github.com/n0tan3rd/wail .
